### ISSUE TITLE
Baixar o projeto para o ambiente local, criar branch e subir ela pro repositório online

### ISSUE THREAD

**Issue by danielmrz-dev** [danielmrz-dev/projeto-angular-I#5]
Instruções detalhadas:
1. Clone o repositório pra sua máquina;
2. Abra o projeto e dê um `git pull` para atualizar seu repositório local com tudo que tiver de mais atualizado no repositório remoto;
3. Crie uma branch pra você trabalhar e dê o nome de `branch/seu-nome`;
4. Faça upload da sua nova branch criada para o repositório online.

**Comment by marcelylobato** [comment]
Criada branch/marcely

**Comment by nattorello** [comment]
Criada branch/natalia

**Comment by Cezaniltom** [comment]
brranch/cezaniltom criada

**Comment by fgarrido-dev** [comment]
Criada branch/felipe

**Comment by danielmrz-dev** [comment]
Finalizado!
